### ISSUE TITLE
email login is broken

### ISSUE THREAD

**Issue by BlackKnight683** [FyreHub/Fyreactyl#13]
/home/container/node_modules/mysql2/lib/packets/packet.js:728
    const err = new Error(message);
                ^
Error: Unknown column 'email' in 'where clause'

**Comment by tovade** [comment]
Full error?

**Comment by BlackKnight683** [comment]
sorry, error on my end.
was fixed

**Comment by GeorgeV220** [comment]
Hello,
how can I fix that?
