### ISSUE TITLE
Question:  Best way to edit theme colors?

### ISSUE THREAD

**Issue by BlackKnight683** [FyreHub/Fyreactyl#14]
I'm unable to locate the `_root.scss` file.
I don't wanna break anything so decided to ask you for the best way to edit the colors :D

**Comment by tovade** [comment]
dark mode: https://github.com/FyreHub/Fyreactyl/blob/master/frontend/assets/css/dark.css
other modes: https://github.com/FyreHub/Fyreactyl/blob/master/frontend/assets/css/customizer.css
