### ISSUE TITLE
Error Login

### ISSUE THREAD

**Issue by Dectectable** [FyreHub/Fyreactyl#17]
![image](https://user-images.githubusercontent.com/75132173/162530489-805052e2-96b8-4fcc-b92e-831db0110247.png)

**Comment by GeorgeV220** [comment]
Please do not use the version from the releases, do a git clone and use a fresh MySQL database. Please make sure that you have set the settings correctly without spelling mistakes.

**Comment by Dectectable** [comment]
![image](https://user-images.githubusercontent.com/75132173/162535142-c84b97e1-54d3-4ade-a424-e26f495ff61b.png)

**Comment by tovade** [comment]
How are you running your site?

**Comment by tovade** [comment]
Actually nvm, this seems to be a configuration error from your side, did you add https/http to your pterodactyl domain in settings.yml?

**Comment by tovade** [comment]
> Please do not use the version from the releases, do a git clone and use a fresh MySQL database. Please make sure that you have set the settings correctly without spelling mistakes.

I will release a new version whenever i have time to fix bugs
