### ISSUE TITLE
Users cannot buy resources

### ISSUE THREAD

**Issue by GeorgeV220** [FyreHub/Fyreactyl#18]
Users cannot buy resources. The error in the dashboard is this but I don't know what is causing it.
![image](https://user-images.githubusercontent.com/30936682/164995394-935084eb-0a37-4816-a9e4-c3071d5e8e0a.png)

Edit:
I tested it and I'm 100% I used numbers

**Comment by tovade** [comment]
Hmm, weird

I'll look at it tonight when imback from school.

**Comment by tovade** [comment]
Hi, can you pull from the latest commit?

I currently don't have a panel available, would be nice if u can confirm it.

Thanks,
Tovade

**Comment by GeorgeV220** [comment]
![image](https://user-images.githubusercontent.com/30936682/165149152-35bdd481-1784-45d0-aae9-184b39e181e7.png)
Same results

**Comment by tovade** [comment]
Alright,

I will fix it when i have my ptero panel back then.

**Comment by tovade** [comment]
This has been fixed in the latest release please use that,
thanks for reporting this bug!
