### ISSUE TITLE
504 gateway timed out

### ISSUE THREAD

**Issue by AndroMaster436** [FyreHub/Fyreactyl#19]
How to fix!?
![Screenshot_2022-05-04-16-56-38-765_com android chrome](https://user-images.githubusercontent.com/87223939/166725107-915f0f38-bafe-439d-b672-cd8d9b48b6d6.jpg)
![Screenshot_2022-05-04-16-57-14-634_com sonelli juicessh](https://user-images.githubusercontent.com/87223939/166725114-82b2a3e9-066a-4ea1-8a50-a9d079f9fbf7.jpg)

**Comment by tovade** [comment]
We do not give support for host's using free domains.
